title: SocioUnido
description: Descripción e introducción a la organización y el trabajo profesional 'SocioUnido'
theme: just-the-docs

url: "https://trabajoprofesional-aggz.github.io"

baseurl: "/.github"
